apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    rolloutproof.dev/service: api
    rolloutproof.dev/version: v2
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry.example.com/api:v2
