apiVersion: rolloutproof.dev/v1alpha1
kind: Schema
tables:
  - name: inventory
    columns:
      - name: id
        type: integer
        default: "nextval('id_seq'::regclass)"
      - name: inventory_count
        type: integer
        nullable: true
